#!/usr/bin/env sh
set -eu

cd "$(dirname "$0")/.."

# Remove build artifacts.
rm -rf -- dist bin

# Remove local runtime artifacts generated by the application.
# .gitkeep files are preserved so the directories remain tracked.
find data -maxdepth 1 -type f ! -name '.gitkeep' -delete 2>/dev/null || true
find logs -maxdepth 1 -type f ! -name '.gitkeep' -delete 2>/dev/null || true

echo "Clean complete."
