$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

# Remove build artifacts.
Remove-Item -LiteralPath (Join-Path $repoRoot "dist") -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $repoRoot "bin") -Recurse -Force -ErrorAction SilentlyContinue

# Remove local runtime artifacts generated by the application.
# .gitkeep files are preserved so the directories remain tracked.
Get-ChildItem (Join-Path $repoRoot "data") -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -ne ".gitkeep" } |
    Remove-Item -Force

Get-ChildItem (Join-Path $repoRoot "logs") -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -ne ".gitkeep" } |
    Remove-Item -Force

Write-Host "Clean complete."
